name: tests

on:
  push:
    paths:
      - 'src/**.php'
      - '.github/workflows/tests.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 75
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.4', '8.5' ]
        laravel: [ '12.50' ]
    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Installing PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, json, sqlite3
          tools: composer:v2
      - name: Lock Laravel Version
        run: composer require "laravel/framework:${{ matrix.laravel }}.*" --no-update -v
      - name: Composer Install
        run: composer install --prefer-dist --no-progress --no-interaction
      - name: Create SQLite Database
        run: mkdir -p database && touch database/database.sqlite
      - name: Run Tests [sqlite]
        run: php vendor/bin/phpunit --stop-on-defect --testdox
        env:
          TEST_DB_ENGINE: sqlite
      - name: Run Tests [postgres 15]
        run: php vendor/bin/phpunit --stop-on-defect --testdox
        env:
          TEST_DB_ENGINE: pgsql
          TEST_DB_PORT: ${{ job.services.postgres15.ports[5432] }}
          TEST_DB_PASSWORD: postgres
      - name: Run Tests [postgres 18]
        run: php vendor/bin/phpunit --stop-on-defect --testdox
        env:
          TEST_DB_ENGINE: pgsql
          TEST_DB_PORT: ${{ job.services.postgres18.ports[5432] }}
          TEST_DB_PASSWORD: postgres
      - name: Run Tests [mysql 8.4]
        run: php vendor/bin/phpunit --stop-on-defect --testdox
        env:
          TEST_DB_ENGINE: mysql
          TEST_DB_PORT: ${{ job.services.mysql8.ports[3306] }}
    services:
      mysql8:
        image: mysql:8.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: vanilo_test
        ports:
          - 3306
      postgres15:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vanilo_test
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres18:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vanilo_test
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
